Якубовская. Задача 6
AngelinaYakubovskaya/spbu-python-course pull request #11
Opened 2024-11-02 16:16 UTC by AngelinaYakubovskaya

теперь с расширением .py

2024-11-03 12:00 UTC, Krekep requested changes
Почти идеально, но небольшие правки нужны

2024-11-03 12:00 UTC, Krekep commented on project/cartesian_tree1.py
Какой смысл несёт в себе 1 в названии?

2024-11-03 12:00 UTC, Krekep commented on project/cartesian_tree1.py
> +    def _rotate_right(self, node):
Не хватает аннотаций типов и документации

2024-11-03 12:00 UTC, Krekep commented on project/cartesian_tree1.py
Добавьте функциональность для вывода дерева в консоль, через существующие методы обхода дерева

2024-11-03 12:00 UTC, Krekep commented on tests/test_cartesian_tree1.py
> +    tree[8] = "eight"
Это, наверное, можно вынести в fixture, т.к. используется во многих тестах

2024-11-03 12:00 UTC, Krekep commented on tests/test_cartesian_tree1.py
> +def test_merge(tree):
В этом тесте tree не используется

2024-11-04 17:58 UTC, AngelinaYakubovskaya commented on project/cartesian_tree1.py
по названию, это я просто загружала заново файлы, и поэтому так обозначила...но в общем исправила название. Функциональность для вывода  в консоль добавила.

2024-11-04 17:58 UTC, AngelinaYakubovskaya commented on project/cartesian_tree1.py
> +    def _rotate_right(self, node):
Добавила аннотации типов и документацию.

2024-11-04 17:58 UTC, AngelinaYakubovskaya commented on tests/test_cartesian_tree1.py
> +    tree[8] = "eight"
Вынесла.

2024-11-04 17:59 UTC, AngelinaYakubovskaya commented on tests/test_cartesian_tree1.py
> +def test_merge(tree):
Исправила тест.

2024-11-04 17:59 UTC, AngelinaYakubovskaya commented
Внесены запрашиваемые изменения.

2024-11-06 07:23 UTC, Krekep approved these changes
Зачтено

2024-11-16 11:06 UTC, merged