Якубовская. Задача 7
AngelinaYakubovskaya/spbu-python-course pull request #13
Opened 2024-11-06 20:46 UTC by AngelinaYakubovskaya

Выполнен анализ датасета Титаник и его визуализация.
Выполнено доп.задание.

2024-11-06 20:47 UTC, AngelinaYakubovskaya commented
Прикрепила и блокнот и ссылку, потому что не поняла, как отображаются графики при загрузке уже блокнота.

2024-11-07 11:32 UTC, AngelinaYakubovskaya commented
Прикрепила ссылку на Google Collab.

2024-11-09 09:42 UTC, Krekep requested changes
Необходимы исправления. Комментарии приложены к самому ноутбуку, если их не видно, сообщите, я продублирую

2024-11-09 09:42 UTC, Krekep commented on README.md
> +- Ссылка на JupyterNotebook (Якубовская) [http://localhost:8888/notebooks/Untitled.ipynb](https://colab.research.google.com/drive/1i4U8AFSslfg8Wt0fTMAXIBYyxVEHBrwO?usp=sharing)
Поправьте название ссылки --- странно кликать на localhost :)

2024-11-09 14:47 UTC, AngelinaYakubovskaya commented on README.md
> +- Ссылка на JupyterNotebook (Якубовская) [http://localhost:8888/notebooks/Untitled.ipynb](https://colab.research.google.com/drive/1i4U8AFSslfg8Wt0fTMAXIBYyxVEHBrwO?usp=sharing)
Название поправила, и там сейчас другая ссылка, я вроде бы сделала, чтобы отображались и графики и всё чтобы правильно загружалось.На всякий случай там ещё ссылка на сам Google Диск.

2024-11-09 14:50 UTC, AngelinaYakubovskaya commented
Комментарии все увидела, внесла запрашиваемые изменения(загрузила файлы датасета, исправила демонстрацию объединения, добавила один график недостающий). Я запустила полностью всё в Google Collab, графики отображаются, надеюсь у вас тоже также будет:)

2024-11-09 16:57 UTC, Krekep requested changes
Необходимы исправления (ссылки приложены правильно, только одна лишняя)

2024-11-09 16:57 UTC, Krekep commented on README.md
> +- Ссылка на JupyterNotebook (Якубовская): [JupyterNotebook файл](http://localhost:8888/notebooks/Jupyter.ipynb)
Ссылка на localhost не нужна, т.к. её никто не сможет открыть. Грубо говоря, команда jupyter notebook поднимает на Вашем компьютере ядро ноутбука, которое слушает порт 8888 и с которым Вы можете взаимодействовать через браузер по ссылке localhost.

2024-11-09 19:42 UTC, AngelinaYakubovskaya commented on README.md
> +- Ссылка на JupyterNotebook (Якубовская): [JupyterNotebook файл](http://localhost:8888/notebooks/Jupyter.ipynb)
Аа, поняла, убрала лишнее. Внесла изменения в графики, чтобы они были читабельны, понятны и информативны.

2024-11-09 19:42 UTC, AngelinaYakubovskaya commented
Внесены запрашиваемый изменения.

2024-11-11 13:29 UTC, Krekep approved these changes
Зачтено

2024-11-16 11:07 UTC, merged