Якубовская. Задача 8.
AngelinaYakubovskaya/spbu-python-course pull request #14
Opened 2024-11-10 08:44 UTC by AngelinaYakubovskaya

Произведён анализ датасета Ирис.
Обучение модели классификации и оценка точности.
Визуализация графиков.
Прикреплён сам ноутбук, файл датасета и ссылка на облачный сервис.

2024-11-11 14:14 UTC, Krekep requested changes
Хорошо, но необходимы исправления

2024-11-11 16:23 UTC, AngelinaYakubovskaya commented
Внесены запрашиваемые изменения(исправлена загрузка файла, действия без sklearn и pandas, изменение визуализации графиков).

2024-11-12 08:34 UTC, Krekep requested changes
Добавьте выводы из экспериментов

2024-11-12 11:48 UTC, AngelinaYakubovskaya commented
Добавлены запрашиваемые изменения(выводы из экспериментов и про genfromtxt тоже(сначала просто посмотрела в google colab, и подумала, что оба комментария надо исправить)).

2024-11-12 12:05 UTC, Krekep approved these changes
Зачтено, выводы лучше оформлять markdown ткестом

2024-11-16 11:11 UTC, merged