Якубовская. Задача 9
AngelinaYakubovskaya/spbu-python-course pull request #15
Opened 2024-11-16 11:24 UTC by AngelinaYakubovskaya

Используя RandomForestClassifier получены значения precision, recall и accuracy. 
Используя LinearRegression получено значение RootMeanSquaredError. 
Сделаны выводы о полученных результатах.

2024-11-17 08:42 UTC, Krekep commented
Расшарьте ноутбук и пинганите меня, когда сделаете

2024-11-17 09:10 UTC, AngelinaYakubovskaya commented
Сделала, прошу прощения, да, там без доступа было.

2024-11-19 14:32 UTC, Krekep requested changes
Необходимы исправления

2024-11-19 18:06 UTC, AngelinaYakubovskaya commented
Внесла запрашиваемые изменения в Google Collab.

2024-11-20 08:56 UTC, Krekep requested changes
Необходимы исправления. И раз Вы приложили файл ноутбука, то приложите ещё датасеты, которые он использует

2024-11-20 18:28 UTC, AngelinaYakubovskaya commented
Внесла изменения, файлы датасета вроде бы загружены в папке project, обновленный файл ноутбука тоже прикрепила в project, ссылка на google colab тоже, соответственно, как и была. Вроде бы всё хорошо.

2024-11-21 12:10 UTC, Krekep approved these changes
Зачтено, но зачем Вы обрабатываете тестовый датасет, если не используете его?

2024-11-22 12:36 UTC, merged