Task10
AngelinaYakubovskaya/spbu-python-course pull request #16
Opened 2024-11-26 17:22 UTC by AngelinaYakubovskaya

Выполнено сравнение методов классификации (найдены данные, произведены первичный и разведочный анализы, выполнены полезные преобразования и получены результаты предсказаний 4 библиотечных реализаций методов классификаций, сделаны выводы).
Прикреплён ноутбук и датасет, а также ссылка на google colab.

2024-11-27 12:24 UTC, Krekep requested changes
В целом всё хорошо, особенно вывод, но небольшие доработки нужны. 
Добавьте больше сравнения моделей, к примеру, графики точности, скорости обучения/скорости работы. Попробуйте посмотреть на результаты моделей при разном уровне препроцессинга данных (без нормализации, с меньшим числом признаков, с PCA/t-SNE, или наоборот расширив признаки, мб устранить выбросы). Сейчас не очевидно, почему Вы именно так преобразовали входные данные (очевиден только отказ от `free sulfur dioxide`, т.к. он коррелирует с другим признаком)

2024-11-27 18:15 UTC, AngelinaYakubovskaya commented
Внесены запрашиваемые изменения. Вроде бы всё поняла, добавила больше сравнений, все комментарии исправила, только ссылка теперь на google colab другая.

2024-11-30 10:07 UTC, Krekep requested changes
Необходимы исправления

2024-12-01 11:30 UTC, AngelinaYakubovskaya commented
Внесены запрашиваемые изменения, ссылка обновлена, ноутбук обновлён, вроде бы ничего не забыла, надеюсь на успешную сдачу!

2024-12-02 14:04 UTC, Krekep requested changes
Не зачёт. Если делаете задание с использованием нейронок, то модерируйте, что они Вам выдают.
Из замечаний:
1. Вывод так и не сделан читаемым
2. Секция с выбросами просто некорректна в контексте всей задачи
3. Сравнительные графики стоило нарисовать друг на друге, как Вы делали в 7 задании
4. Местами Вы нормально отображаете confusion matrix, местами просто печатаете
5. Удаление дубликатов не совсем корректно
6. Вы дважды обучаете модели на одних и тех же данных в пунктах "коррелирующие признаки" и "удаление выбросов"
7. Как соотносятся выводы для KNN в пунктах про PCA и корреляцию? В обоих пунктах просто удаляются признаки
8. Слишком много дублирующегося кода
9. Точность моделей в глобальных выводах не соотносится с результатами в ноутбуке
10. Насколько я вижу (возможно проглядел) у Вас нет обучения моделей без SMOTE, но в глобальных выводах есть пункт про его влияние на результат обучения моделей
11. Не создавайте на каждое ревью новый ноутбук, работайте в исходном

2024-12-02 16:00 UTC, closed without merging