Якубовская. Задача 2
AngelinaYakubovskaya/spbu-python-course pull request #4
Opened 2024-10-16 16:34 UTC by AngelinaYakubovskaya

Добавлены запрашиваемые изменения.

2024-10-18 18:24 UTC, Krekep requested changes
К сожалению, не могу зачесть задачу. Замечания:
1. **Не сделан обязательный пункт про кэширование результатов**
2. Не удаляйте файлы прошлых заданий
3. Если слили по ошибке, то надо отменить изменения в `main` (самый простой и не элегантный способ --- закоммитить удаление случайно добавленных файлов).

2024-10-18 18:24 UTC, Krekep commented on project/decorate.py
> +    return x, y  # Возвращаем значения x и y
Эти функции должны быть в тестах, а не в исходниках

2024-10-18 18:24 UTC, Krekep commented on project/decorate.py
> +    return random.randint(0, 100)
Этого тоже не должно быть в исходниках

2024-10-18 18:24 UTC, Krekep commented on tests/test_decorate.py
> +    assert result1[0] != result1[1]  # Проверка, что значения разные
С большой вероятностью значения будут одинаковыми. Лучше используйте другие способы проверки того, что Evaluated действительно выполняется каждый раз при вызове функции

2024-10-18 18:24 UTC, Krekep commented on tests/test_curry_uncarry.py
Не хватает тестов
- Со встроенными функциями
- Проверяющие, что арность функции "заморожена" и ей нельзя передать больше аргументов
- Проверяющие, что вы не можете передать функции больше одного аргумента за раз

2024-10-18 18:24 UTC, Krekep commented on tests/test_decorate.py
Не хватает теста проверяющего, что у функции один аргумент может быть Isolated, а второй Evaluated

2024-11-02 10:11 UTC, AngelinaYakubovskaya commented
Внесла изменения, сейчас вроде бы все требования выполнены, всё хорошо.

2024-11-02 10:20 UTC, AngelinaYakubovskaya commented
Внесла изменения, сейчас вроде бы все требования выполнены, всё хорошо.

2024-11-06 07:53 UTC, Krekep requested changes
Замечания:
1) В который раз пишу Вам --- не удаляйте файлы
2) Вы не добавили тест, проверяющий, что нельзя в каррированную функцию передать больше одного аргумента (окей, из кода видно, но тест нужен)
3) Не выполнили формальные требования по оформлению ПР

Т.к. задание выполнено, к нему нет вопросов, и это третья попытка сдачи, то окей, после того, как поправите замечания выше зачту задание

2024-11-06 07:53 UTC, Krekep commented on project/curry_uncarry.py
uncurry

2024-11-14 18:20 UTC, AngelinaYakubovskaya commented on project/decorate.py
> +    return x, y  # Возвращаем значения x и y
Исправлена реализация тестов.

2024-11-14 18:21 UTC, AngelinaYakubovskaya commented on project/decorate.py
> +    return random.randint(0, 100)
Исправлена реализация тестов.

2024-11-14 18:21 UTC, AngelinaYakubovskaya commented on tests/test_decorate.py
> +    assert result1[0] != result1[1]  # Проверка, что значения разные
Исправлена реализация теста.

2024-11-14 18:21 UTC, AngelinaYakubovskaya commented on tests/test_curry_uncarry.py
Добавлены необходимые тесты.

2024-11-14 18:22 UTC, AngelinaYakubovskaya commented on tests/test_decorate.py
Добавлены необходимые тесты.

2024-11-14 18:22 UTC, AngelinaYakubovskaya commented on project/curry_uncarry.py
Исправила опечатки в названии.

2024-11-14 18:27 UTC, AngelinaYakubovskaya commented
Отменены коммиты со случайным удалением файлов, добавлены необходимые тесты, по требованиям ПР это вроде же про ответы на комментарии?  Я забыла, да, ответить( 
Дополнила всё.
(Написана функция curry_explicit(функция, арность) и парная к ней функция uncurry_explicit(функция, арность).
Реализован декоратор для кэширования результатов выполнения функции.
Написан декоратор @smart_args, который анализирует типы значений аргументов функции по умолчанию и, в зависимости от этого, копирует и/или вычисляет их перед выполнением функции.)

2024-11-15 11:02 UTC, Krekep approved these changes
Зачтено
Слейте все зачтённые задачи

2024-11-16 11:05 UTC, merged