Якубовская. Задание 3
AngelinaYakubovskaya/spbu-python-course pull request #5
Opened 2024-10-16 18:49 UTC by AngelinaYakubovskaya

Написано генераторное выражение для четырехмерного набора векторов RGBA модели.
Реализована функцию-генератор последовательности простых чисел. 
Добавлены тесты покрывающие реализованную функциональность.

2024-10-18 18:28 UTC, Krekep requested changes
Необходимы исправления

2024-10-18 18:28 UTC, Krekep commented on project/rgba.py
> +                    yield (red, green, blue, alpha)
Это не генераторное выражение.
Также, формально Вы правы, но перепишите с использованием `if` для демонстрации того, что Вы это умеете

2024-10-18 18:28 UTC, Krekep commented on project/generator.py
> +        gen = prime_generator()
Генератор не меняется, нет нужды создавать его каждый раз, особенно при условии того, что `k` на вход подаются в неубывающем порядке

2024-10-22 08:21 UTC, AngelinaYakubovskaya commented on project/rgba.py
> +                    yield (red, green, blue, alpha)
Переписала код так, чтобы он наглядно показывал, как формируется последовательность RGBA, с использованием циклов и условного выражения.

2024-10-22 08:21 UTC, AngelinaYakubovskaya commented on project/generator.py
> +        gen = prime_generator()
Изменила код с учётом комментария.

2024-10-22 08:21 UTC, AngelinaYakubovskaya commented
Внесла запрашиваемые изменения, создам новый pull request.

2024-10-22 08:22 UTC, closed without merging