Якубовская. Задача 4
AngelinaYakubovskaya/spbu-python-course pull request #6
Opened 2024-10-21 19:42 UTC by AngelinaYakubovskaya

Реализован паттерн "пул потоков" с учётом указанных ограничений и допущений

2024-10-21 20:01 UTC, Krekep requested changes
Необходимы исправления

2024-10-21 20:01 UTC, Krekep commented on project/thread_pool.py
> +import queue
Этот класс реализует в себе методы для работы с потоками. Из пакетов для работы с многопоточностью по условию задачи разрешён только `threading`

2024-10-21 20:01 UTC, Krekep commented on tests/test_thread_pool.py
> +    assert len(pool.threads) == 5, "Incorrect number of threads created in the pool."
Этот тест проверяет, что Вы занесли в массив 5 элементов, а не то, что у в данный момент времени у Вас 5 рабочих потоков присутствует. Здесь лучше использовать `active_count()`

2024-10-21 20:01 UTC, Krekep commented on tests/test_thread_pool.py
Добавьте тесты, проверяющие, что у Вас действительно выполняются все добавленные в ThreadPool задачи

2024-10-22 07:45 UTC, AngelinaYakubovskaya commented on project/thread_pool.py
> +import queue
Поняла, теперь использую только threading для управления потоками и задачами.

2024-10-22 07:45 UTC, AngelinaYakubovskaya commented on tests/test_thread_pool.py
> +    assert len(pool.threads) == 5, "Incorrect number of threads created in the pool."
Исправила тест для проверки активных потоков с помощью threading.active_count().

2024-10-22 07:45 UTC, AngelinaYakubovskaya commented on tests/test_thread_pool.py
Добавлены тесты для всех методов класса ThreadPool.

2024-10-22 07:45 UTC, AngelinaYakubovskaya commented
Внесла изменения, создам новый pull request.

2024-10-22 07:45 UTC, closed without merging