Якубовская. Задача 3
AngelinaYakubovskaya/spbu-python-course pull request #8
Opened 2024-10-22 08:23 UTC by AngelinaYakubovskaya

Добавлены запрашиваемые изменения.

2024-10-22 08:38 UTC, Krekep requested changes
Необходимы исправления

2024-10-22 08:38 UTC, Krekep commented on project/generator.py
> +        gen = prime_generator()
Так Вы же не исправили это замечание. Вам наоборот не нужно создавать новый экземпляр генератора для каждого вызова. Достаточно один раз его создать и пользоваться

2024-10-22 08:38 UTC, Krekep commented on project/generator.py
> +    def wrapper(k):
Не хватает аннотаций типов

2024-10-22 08:38 UTC, Krekep commented on tests/test_generator.py
> +        (5, 11),  # 5th prime number is 11
Добавьте тест, где запрашиваете одно и тоже простое число несколько раз (к примеру, 2 раза просите получить второе простое число)

2024-10-22 17:50 UTC, AngelinaYakubovskaya commented on project/generator.py
> +        gen = prime_generator()
Теперь создаём генератор один раз и используем его для получения следующего простого числа при каждом вызове.

2024-10-22 17:50 UTC, AngelinaYakubovskaya commented on project/generator.py
> +    def wrapper(k):
Добавлены типизация аргументов и возвращаемых значений в функцию.

2024-10-22 17:50 UTC, AngelinaYakubovskaya commented on tests/test_generator.py
> +        (5, 11),  # 5th prime number is 11
Добавлен новый тест для проверки повторного запроса одного и того же простого числа.

2024-10-22 17:50 UTC, AngelinaYakubovskaya commented
Внесены запрашиваемые изменения.

2024-11-01 19:55 UTC, AngelinaYakubovskaya commented
Исправила, вроде бы сейчас всё, как должно быть.

2024-11-02 07:43 UTC, Krekep approved these changes
Зачтено

2024-11-02 07:43 UTC, Krekep commented on project/generator.py
> +prime_cache: List[int] = []
Кэш не нужен, т.к. номера простых чисел по условию задания приходят в неубывающем порядке

2024-11-16 11:06 UTC, merged