Якубовская. Задача 5
AngelinaYakubovskaya/spbu-python-course pull request #9
Opened 2024-10-27 09:47 UTC by AngelinaYakubovskaya

Реализована игра рулетка с учётом требований.
Для реализованной игры построена UML диаграмма классов.

2024-10-28 08:27 UTC, Krekep requested changes
Необходимы исправления
Особое внимание обратите на то, что Вы не реализовали игру рулетка по факту. Нет полей, на которые ставят игроки, а также игроки не должны решать выиграли они или нет, это должен делать крупье.
Не забудьте поменять UML диаграмму классов соответственно исправлениям

2024-10-28 08:27 UTC, Krekep commented on docs/uml_diagram.puml
> +abstract class BasePlayer {
В коде этот класс называется по другому

2024-10-28 08:27 UTC, Krekep commented on project/bots/martingale_bot.py
> +        print(f"{self.name} places a Martingale bet of {bet}")
Идейно этот класс должен только делать ставки и хранить некоторую информацию. Вывод в консоль это побочное действие, которого он не должен делать, при этом допустима реализация методов для получения внутреннего состояния Игрока

2024-10-28 08:27 UTC, Krekep commented on project/bots/passive_aggressive_bot.py
> +        print(
Same

2024-10-28 08:27 UTC, Krekep commented on project/bots/percentage_bot.py
> +        print(f"{self.name} places a percentage bet of {bet}")
Same

2024-10-28 08:27 UTC, Krekep commented on project/game.py
> +            print(f"\n=== Round {self.current_step + 1} ===")
Аналогично Игрокам, этот класс должен хранить и поддерживать изменение состояния игры, но не выводить информацию в консоль.

2024-10-28 08:27 UTC, Krekep commented on project/bots/percentage_bot.py
> +            tuple[int, bool]: The amount bet and whether the bet was successful.
Игрок не определяет удачная у него ставка или нет. Это делает крупье

2024-10-28 08:27 UTC, Krekep commented on project/main.py
Как-будто этот файл у Вас в примерах есть, так что здесь он не нужен

2024-10-30 15:29 UTC, AngelinaYakubovskaya commented on docs/uml_diagram.puml
> +abstract class BasePlayer {
Теперь вроде бы должно совпадать.

2024-10-30 15:30 UTC, AngelinaYakubovskaya commented on project/bots/martingale_bot.py
> +        print(f"{self.name} places a Martingale bet of {bet}")
Исправила реализацию игры.

2024-10-30 15:30 UTC, AngelinaYakubovskaya commented on project/bots/passive_aggressive_bot.py
> +        print(
Исправила реализацию игры.

2024-10-30 15:30 UTC, AngelinaYakubovskaya commented on project/bots/percentage_bot.py
> +        print(f"{self.name} places a percentage bet of {bet}")
Исправила реализацию игры.

2024-10-30 15:30 UTC, AngelinaYakubovskaya commented on project/game.py
> +            print(f"\n=== Round {self.current_step + 1} ===")
Исправила реализацию игры.

2024-10-30 15:30 UTC, AngelinaYakubovskaya commented on project/bots/percentage_bot.py
> +            tuple[int, bool]: The amount bet and whether the bet was successful.
Исправила реализацию игры.

2024-10-30 15:30 UTC, AngelinaYakubovskaya commented on project/main.py
Удалила файл за ненадобностью.

2024-10-30 15:30 UTC, AngelinaYakubovskaya commented
Добавлены запрашиваемые изменения(там будут некоторые удаления, это случайно добавленные файлы).

2024-11-01 08:28 UTC, Krekep requested changes
Хорошо, но надо исправить диаграмму и магические константы

2024-11-01 08:28 UTC, Krekep commented on project/bots/martingale_bot.py
> +        bet = {"type": "color", "value": "red", "amount": self.current_bet}
Магические константы это [антипаттерн в программировании](https://en.wikipedia.org/wiki/Anti-pattern). У Вас в качестве магических констант выступают, к примеру, типы ставок, цвета и поля ставки, перепишите код без них
Вместо словаря, стоит использовать класс/перечисление. Не забудьте отобразить его на диаграмме классов

2024-11-01 08:28 UTC, Krekep commented on project/bots/uml_diagram.puml
Вроде бы этот файл дубликат

2024-11-01 08:28 UTC, Krekep commented on project/game.py
> +        }
Как вариант, можно хранить историю последних `k` раундов, чтобы вывод был более информативен (не обязательно)

2024-11-01 08:28 UTC, Krekep commented on docs/uml_diagram.png
А без `--` puml не рисует разделение?
Комментарий по делу --- на диаграмме поля отображены приватными, но в коде это никак не *подчёркивается*. Также метод `play_round` должен быть приватным и у крупье методов в коде больше, чем на диаграмме, тоже не порядок

2024-11-01 08:50 UTC, Krekep commented on project/bots/martingale_bot.py
> +        bet = {"type": "color", "value": "red", "amount": self.current_bet}
Не ту ссылку прикрепил, держите [правильную](https://en.wikipedia.org/wiki/Magic_number_(programming))

2024-11-02 19:21 UTC, AngelinaYakubovskaya commented on project/bots/martingale_bot.py
> +        bet = {"type": "color", "value": "red", "amount": self.current_bet}
Переписала код.

2024-11-02 19:22 UTC, AngelinaYakubovskaya commented on project/bots/uml_diagram.puml
Да, вы правы, удалила.

2024-11-02 19:22 UTC, AngelinaYakubovskaya commented on project/game.py
> +        }
Хорошо

2024-11-02 19:22 UTC, AngelinaYakubovskaya commented on docs/uml_diagram.png
Изменила диаграмму.

2024-11-02 19:22 UTC, AngelinaYakubovskaya commented
Внесены запрашиваемый изменения.

2024-11-06 11:46 UTC, Krekep approved these changes
Зачтено

2024-11-06 11:46 UTC, Krekep commented on project/croupier.py
> +        """
Документация на английском должна быть

2024-11-06 11:46 UTC, Krekep commented on project/croupier.py
> +        number = random.randint(0, 36)
Не хватает документации

2024-11-06 11:46 UTC, Krekep commented on project/croupier.py
> +        return {"number": number, "color": color}
Ячейку колеса тоже можно представить в виде класса/перечисления/именованного кортежа

2024-11-16 11:06 UTC, merged